version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: bookstore_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  django_app:
    build:
      context: ./django_app
    container_name: django_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bookstore
      DB_USER: user
      DB_PASSWORD: password
      SECRET_KEY: your-secret-key  
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:

