# Generated by Django 4.2.16 on 2024-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='Unknown', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(default='Unknown', max_length=100)),
                ('publication_year', models.IntegerField(null=True)),
                ('publisher', models.CharField(default='Unknown', max_length=255)),
                ('description', models.TextField(default='Empty')),
                ('review_count', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
