# Generated by Django 4.2.16 on 2024-11-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
